{{- if .Values.websocket.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "xagent.fullname" . }}-websocket
  labels:
    {{- include "xagent.labels" . | nindent 4 }}
    app.kubernetes.io/component: websocket
  {{- with .Values.websocket.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.websocket.service.type }}
  ports:
    - port: {{ .Values.websocket.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "xagent.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: websocket
{{- end }}
